#!/bin/bash

# Create a symbolic link in the home directory
create_symlink() {
    if [ -z "$1" ]; then
        echo "usage: create_symlink \"path/to/dotfile\""
    else
        if [ ! -z "$(ls -A $1)" ]; then
            # Bash string manipulation, equivalent to 'basename'
            # See: http://tldp.org/LDP/LG/issue18/bash.html
            FILE_NAME=${1##*/}
            # -s create symlink
            # -f if target file exists, first unlink to allow linking
            # -n do not follow if target file is a symlink
            ln -sfn "$(pwd)/$1" "$HOME/$FILE_NAME"
            # Print success message
            echo "symlink created: $HOME/$FILE_NAME -> $(pwd)/$1"
        fi
    fi
}

# Git
create_symlink "git/.gitconfig"
create_symlink "git/.githelpers"
